# Используем официальный образ Node.js версии 18 (LTS)
FROM node:18

# Создаем рабочую директорию внутри контейнера
WORKDIR /usr/src/app

# Копируем package.json и package-lock.json (если есть)
COPY package*.json ./

# Устанавливаем все зависимости
RUN npm install

# Копируем весь остальной код приложения
COPY . .

# Сообщаем Docker, что приложение будет слушать порт 8080
EXPOSE 3000

# Команда для запуска приложения
CMD ["node", "server.js"]